[theme]
base                    = "dark"
primaryColor            = "#3b82f6"
backgroundColor         = "#0d1117"
secondaryBackgroundColor= "#161b26"
textColor               = "#e6eaf2"

[client]
toolbarMode = "minimal"
